// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPfvAXb08O6wJw5sHAcrETCI4KMLD_eTc',
    appId: '1:669589728354:web:d20d41c1eb6081f0d2b53b',
    messagingSenderId: '669589728354',
    projectId: 'e-commerce-app-cb443',
    authDomain: 'e-commerce-app-cb443.firebaseapp.com',
    storageBucket: 'e-commerce-app-cb443.appspot.com',
    measurementId: 'G-N0F02FV9MT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_jSoyChgCDkDX-GO98-fr84k9oCh7MrI',
    appId: '1:669589728354:ios:68f117246b8a4723d2b53b',
    messagingSenderId: '669589728354',
    projectId: 'e-commerce-app-cb443',
    storageBucket: 'e-commerce-app-cb443.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_jSoyChgCDkDX-GO98-fr84k9oCh7MrI',
    appId: '1:669589728354:ios:68f117246b8a4723d2b53b',
    messagingSenderId: '669589728354',
    projectId: 'e-commerce-app-cb443',
    storageBucket: 'e-commerce-app-cb443.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy1D7QpssfdT24Han4sqJA5Qwgn3qJ8o4',
    appId: '1:669589728354:android:f9deed8e40249575d2b53b',
    messagingSenderId: '669589728354',
    projectId: 'e-commerce-app-cb443',
    storageBucket: 'e-commerce-app-cb443.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPfvAXb08O6wJw5sHAcrETCI4KMLD_eTc',
    appId: '1:669589728354:web:49b00ebcad04aeb5d2b53b',
    messagingSenderId: '669589728354',
    projectId: 'e-commerce-app-cb443',
    authDomain: 'e-commerce-app-cb443.firebaseapp.com',
    storageBucket: 'e-commerce-app-cb443.appspot.com',
    measurementId: 'G-XQW3S8HLNF',
  );

}